services:
  api:
    container_name: BoardGame
    depends_on:
      redis-service:
          condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:80"
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80'
  redis-service:
    container_name: redis-service
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]