//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu_Practice {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Menu_Practice.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇你要出的卡 的當地語系化字串。
        /// </summary>
        internal static string ChooseCard {
            get {
                return ResourceManager.GetString("ChooseCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose a character 的當地語系化字串。
        /// </summary>
        internal static string ChooseCharacter {
            get {
                return ResourceManager.GetString("ChooseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇你要取得的卡 的當地語系化字串。
        /// </summary>
        internal static string ChooseObtainCard {
            get {
                return ResourceManager.GetString("ChooseObtainCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Choose an opponent 的當地語系化字串。
        /// </summary>
        internal static string ChooseOppoCharacter {
            get {
                return ResourceManager.GetString("ChooseOppoCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 所選卡片剩餘0張，請選別張卡 的當地語系化字串。
        /// </summary>
        internal static string ChooseOtherCard {
            get {
                return ResourceManager.GetString("ChooseOtherCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MainMenu 的當地語系化字串。
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;https://localhost:44318/&quot; 的當地語系化字串。
        /// </summary>
        internal static string TempDomainName {
            get {
                return ResourceManager.GetString("TempDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刺客 的當地語系化字串。
        /// </summary>
        internal static string 刺客 {
            get {
                return ResourceManager.GetString("刺客", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 士兵 的當地語系化字串。
        /// </summary>
        internal static string 士兵 {
            get {
                return ResourceManager.GetString("士兵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詐欺師* 的當地語系化字串。
        /// </summary>
        internal static string 詐欺師_ {
            get {
                return ResourceManager.GetString("詐欺師*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說客 的當地語系化字串。
        /// </summary>
        internal static string 說客 {
            get {
                return ResourceManager.GetString("說客", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 領主 的當地語系化字串。
        /// </summary>
        internal static string 領主 {
            get {
                return ResourceManager.GetString("領主", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 騎士 的當地語系化字串。
        /// </summary>
        internal static string 騎士 {
            get {
                return ResourceManager.GetString("騎士", resourceCulture);
            }
        }
    }
}
